### ISSUE TITLE
alb idleTimeout

### ISSUE THREAD

**Issue by plarsson** [pahud/cdk-fargate-patterns#101]
Can we add idleTimeout to ApplicationLoadBalancer

**Comment by plarsson** [comment]
Hi `idleTimeout` wasn't added?  wrong PR?

**Comment by neilkuan** [comment]
sorry, my mistake. 😂

**Comment by neilkuan** [comment]
Hi @plarsson, now you can try it.

**Comment by plarsson** [comment]
Hi great!
however I think we need to be able to specify separate idleTimeout for internal vs external ?

**Comment by plarsson** [comment]
Hi @neilkuan  did you see my comment above?

**Comment by neilkuan** [comment]
sorry, I missed it , maybe we can create another issue and PR to solve that issue.
