### ISSUE TITLE
Specific idleTimeout for ALB

### ISSUE THREAD

**Issue by plarsson** [pahud/cdk-fargate-patterns#122]
It should be possible to configure a specific idleTimeout for each ALB. As it is now the idleTimeout is shared and affects both ALB:s

**Comment by pahud** [comment]
@plarsson I am curious about the scenario. Can you share a little bit about why you need different `idleTimeout` values?

**Comment by plarsson** [comment]
Yes, 

The reason behind this is I noticed gRPC disconnected and reconnected every 60s if services was idle (the alb has a default 60 seconds default idle) . It looks like the recommendation it to raise the idle timeout on alb when using gRPC, so it's very likely you want different idle timeout settings external vs internal.

https://stackoverflow.com/questions/66818645/http2-ping-frames-over-aws-alb-grpc-keepalive-ping

So it looks like the recommendation is to have a high idle timeout if using gRPC and I was thinking you might not want to have the same high idle timeout on the external ALB?

**Comment by neilkuan** [comment]
Hi @plarsson , now you can try it. :)
