### ISSUE TITLE
externalOnly ?

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-fargate-patterns#19]
For some internet-facing only services, the internal ALB is not required. We should allow this scenario to create only the EXTERNAL ALB.

## Possible solutions

1. Introduce the `externalOnly` property and avoid using both `internalOnly` and `extenralOnly`
2. Introduce the `accessibility` enum property with
     `accessibility.INTERNAL_ONLY`
    ` accessibility.EXTERNAL_ONLY`
     `accessibility.BOTH` (default value)

**Comment by neilkuan** [comment]
LGTM
