### ISSUE TITLE
docker build failed with Laravel

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-fargate-patterns#35]
On my laptop
<img width="1139" alt="圖片" src="https://user-images.githubusercontent.com/278432/124344469-f8f94e00-dc04-11eb-8222-6d27349aa782.png">

On github codespaces
<img width="1440" alt="圖片" src="https://user-images.githubusercontent.com/278432/124344485-14fcef80-dc05-11eb-9faf-88526f439506.png">

**Comment by dwchiang** [comment]
Let me check on it this week.

**Comment by dwchiang** [comment]
Working on it. Also checking on Bitnami Laravel image.
