### ISSUE TITLE
Laravel high-level construct

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-fargate-patterns#42]
Now that we are going to have a working sample for Laravel  https://github.com/pahud/cdk-fargate-patterns/pull/41

Similar to [WordPress()](https://github.com/pahud/cdk-fargate-patterns/blob/ec9dc6ee8c7acf775b169a8a203d6d7275dd40a4/src/wordpress.ts#L72), wondering if we could have a high-level construct like ` new Laravel()` and everything would be all set?

The building experience should be like

```ts

new Laravel(scope, id, {
   spot: true,  // make it FARGATE_SPOT
   path,  // path to local Laravel code base
}
```

@dwchiang @clarencetw @neilkuan  wdyt?

**Comment by dwchiang** [comment]
Sounds great! Let me try it.

**Comment by pahud** [comment]
> Sounds great! Let me try it.

I'll submit an initial PR for it shortly.
