### ISSUE TITLE
laravel-bitnami docker build failed

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-fargate-patterns#47]
<img width="1360" alt="圖片" src="https://user-images.githubusercontent.com/278432/124856434-164f6300-dfdd-11eb-8d4e-86246cd57181.png">

**Comment by pahud** [comment]
@dwchiang  can you take a look?

**Comment by dwchiang** [comment]
Yes. Let me take a look.

**Comment by dwchiang** [comment]
It should be caused by not yet run `composer install` in the myapp folder. As a demo scenario, I will try to put `compsoer install` in the Dockerfile. Let me add it later on.
