### ISSUE TITLE
Add ALB gRPC support

### ISSUE THREAD

**Issue by plarsson** [pahud/cdk-fargate-patterns#69]
background: https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/

I think we need to be able to specify protocolVersion on the target group? Also we should be able to define a healthcheck using "healthyGrpcCodes", perhaps already possible? 

Thanks

**Comment by pahud** [comment]
Hi @plarsson 

Thanks for the feedback.

Looks like we can expose some target group properties to allow users specify different `protocol` and `protocolVersion`
<img width="863" alt="圖片" src="https://user-images.githubusercontent.com/278432/125893313-e64dd8c0-be34-4e39-ac07-7ff001cc7266.png">

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-protocol

In this case we should be able to make it gRPC with ALB.

**Comment by pahud** [comment]
In terms of the `healthyGrpcCodes` I believe we simply need to customize the statusCode in the [healthcheck](https://github.com/pahud/cdk-fargate-patterns/blob/a962bb0cb1e041a819dc020c106b08685843978e/src/main.ts#L89) property, which is already exposed and allow users to customize.



![](https://d2908q01vomqb2.cloudfront.net/da4b9237bacccdf19c0760cab7aec4a8359010b0/2020/10/09/aws-alb-grpc-target-group-health-check-code-1024x508.png)

**Comment by pahud** [comment]
Hi @plarsson feel free to try this construct with gRPC support and let us know if it works in your environment.

Thanks.

**Comment by pahud** [comment]
@all-contributors please add @plarsson  for ideas

**Comment by plarsson** [comment]
Perfect, I'll try this out in a few days. Thanks!

**Comment by plarsson** [comment]
I did some initial tests with gRPC now, It works just fine 👍  Thanks!
