### ISSUE TITLE
Cannot access the ecs task due to the 「enable_execute_command」 is not enable 

### ISSUE THREAD

**Issue by paper5487** [pahud/cdk-fargate-patterns#7]
When attempting to access the fragate tasks ,aws cli errors out with the execute cammand is not enable.

aws cli version:aws-cli/1.19.97 Python/3.7.9 Linux/4.14.232-176.381.amzn2.x86_64 botocore/1.20.97
![iShot2021-06-21 23 25 24](https://user-images.githubusercontent.com/15643225/123041564-0dc92b00-d428-11eb-9e5b-7516501faaa5.jpg)

**Comment by pahud** [comment]
@all-contributors please add @paper5487  for bug
