### ISSUE TITLE
support import exist ECS Cluster.

### ISSUE THREAD

**Issue by neilkuan** [pahud/cdk-fargate-patterns#94]
support import exist ECS Cluster.

Now use `new DualAlbFargateService()` will create a new ECS cluster.

see
https://github.com/pahud/cdk-fargate-patterns/blob/9ecc250e80a2be6aca0d7a632899449611cb826f/src/main.ts#L197-L200

Maybe can make one more option allows the user to specify an existing cluster.

**Comment by pahud** [comment]
Agree! Let's do it!
